
server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/www?useSSL=false&serverTimezone=UTC
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: "mySecretKey1234567890mySecretKey1234567890" # 실제 운영 환경에서는 더 복잡하고 안전한 키 사용
  expiration-time: 86400000 # 1일 (밀리초)

weather:
  service-key: "XEa7BTZ7ZMxqQCg482IIMtEZa6VrcnMM6GTmK26ZO8nThpY1v5Og70vIkgH4Ce%2B0AjZwa39omHBbOxj5I0jJLQ%3D%3D"



